### ISSUE TITLE
Glide loaded images are rotated

### ISSUE THREAD

**Issue by eicm** [willblaschko/header-footer-recycler-view#1]
I tired the library with Glide library to load images to RecyclerView and Images were rotated.

**Comment by willblaschko** [comment]
Was the Glide library loading the images correctly when not using this
adapter extension? The library itself should not change how images are
being loaded.

**Comment by eicm** [comment]
Yes it works correctly when I I bind inside my extended adapter and that's the strange behaviour as  everything is almost the same in my adapter and in extended Intermediary

**Comment by eicm** [comment]
My bad I was passing my mediaType (0, 1, 2, 3) to orientation field I had for taking care of media orientation and that was causing the rotations

**Comment by willblaschko** [comment]
No worries, closing this issue :)
